const PRIMARY_BLUE = "#234DC4";
const PRIMARY_GRAY = "#EBEFF5";
const PRIMARY_WHITE = "#F6F6F6";
const SECONDARY_WHITE = "#FFFFFF";
// const PRIMARY_WHITE = "#FFFFFF";
// "#B0BEC5",

export {
  PRIMARY_BLUE,
  PRIMARY_GRAY,
  PRIMARY_WHITE,
  SECONDARY_WHITE,
};
