const DO_HYEON_400_REGULAR = "DoHyeon_400Regular";
const BLACK_HANS_SANS_400_REGULAR = "BlackHanSans_400Regular"
const NANUM_GOTHIC_CODING_400_REGULAR = "NanumGothicCoding_400Regular";
const NANUM_GOTHIC_CODING_700_BOLD = "NanumGothicCoding_700Bold";
const NOTO_SANS_KR_100_THIN = "NotoSansKR_100Thin";
const NOTO_SANS_KR_300_LIGHT = "NotoSansKR_300Light";
const NOTO_SANS_KR_400_REGULAR = "NotoSansKR_400Regular";
const NOTO_SANS_KR_500_MEDIUM = "NotoSansKR_500Medium";
const NOTO_SANS_KR_700_BOLD = "NotoSansKR_700Bold";
const NOTO_SANS_KR_900_BLACK = "NotoSansKR_900Black";

const PRIMARY_FONT = "NotoSansKR_500Medium";
const SECONDARY_FONT = "NotoSansKR_400Regular";
const TERTIARY_FONT = "NotoSansKR_300Light";

export {
  PRIMARY_FONT,
  SECONDARY_FONT,
  TERTIARY_FONT,

  DO_HYEON_400_REGULAR,
  BLACK_HANS_SANS_400_REGULAR,
  NANUM_GOTHIC_CODING_400_REGULAR,
  NANUM_GOTHIC_CODING_700_BOLD,
  NOTO_SANS_KR_100_THIN,
  NOTO_SANS_KR_300_LIGHT,
  NOTO_SANS_KR_400_REGULAR,
  NOTO_SANS_KR_500_MEDIUM,
  NOTO_SANS_KR_700_BOLD,
  NOTO_SANS_KR_900_BLACK,
};
