const DO_HYEON_400_REGULAR = "DoHyeon_400Regular";
const BLACK_HANS_SANS_400_REGULAR = "BlackHanSans_400Regular"
const NANUM_GOTHIC_CODING_400_REGULAR = "NanumGothicCoding_400Regular";
const NANUM_GOTHIC_CODING_700_BOLD = "NanumGothicCoding_700Bold";

export {
  DO_HYEON_400_REGULAR,
  BLACK_HANS_SANS_400_REGULAR,
  NANUM_GOTHIC_CODING_400_REGULAR,
  NANUM_GOTHIC_CODING_700_BOLD,
};
