const MATCH_HEADER_HEIGHT = 80;
const MATCH_HEADER_DROPDOWN_WIDTH = 60;
const MATCH_HEADER_DROPDOWN_HEIGHT = 30;

const MY_TEAM_HEADER_HEIGHT = 80;
const MY_TEAM_HEADER_DROPDOWN_WIDTH = 60;
const MY_TEAM_HEADER_DROPDOWN_HEIGHT = 30;

const MY_TEAM_OVERVIEW_HEIGHT = 150;
const MY_TEAM_OVERVIEW_WIDTH = 300;
const MY_TEAM_OVERVIEW_TITLE_FONT_SIZE = 14;
const MY_TEAM_OVERVIEW_CONTENT_FONT_SIZE = 14;

export {
  MATCH_HEADER_HEIGHT,
  MATCH_HEADER_DROPDOWN_WIDTH,
  MATCH_HEADER_DROPDOWN_HEIGHT,

  MY_TEAM_HEADER_HEIGHT,
  MY_TEAM_HEADER_DROPDOWN_WIDTH,
  MY_TEAM_HEADER_DROPDOWN_HEIGHT,

  MY_TEAM_OVERVIEW_HEIGHT,
  MY_TEAM_OVERVIEW_WIDTH,
  MY_TEAM_OVERVIEW_TITLE_FONT_SIZE,
  MY_TEAM_OVERVIEW_CONTENT_FONT_SIZE,
}
