import * as device from "./device";

const DEVICE_WIDTH = device.WIDTH;
const DEVICE_HEIGHT = device.HEIGHT;

const TAB_NAVIGATOR_HEIGTH = 60;
const TAB_NAVIGATOR_LABEL_FONT_SIZE = 12;
const TAB_NAVIGATOR_LABEL_MARGIN_BOTTOM = 5;

const MATCH_HEADER_HEIGHT = 80;
const MATCH_HEADER_DROPDOWN_WIDTH = 60;
const MATCH_HEADER_DROPDOWN_HEIGHT = 30;

const MY_TEAM_HEADER_HEIGHT = 80;
const MY_TEAM_HEADER_DROPDOWN_WIDTH = 60;
const MY_TEAM_HEADER_DROPDOWN_HEIGHT = 30;

const MY_TEAM_OVERVIEW_HEIGHT = 100;
const MY_TEAM_OVERVIEW_WIDTH = 0.9 * DEVICE_WIDTH;
const MY_TEAM_OVERVIEW_TITLE_FONT_SIZE = 14;
const MY_TEAM_OVERVIEW_CONTENT_FONT_SIZE = 14;

const MY_TEAM_MEMBER_HEIGHT = 150;
const MY_TEAM_MEMBER_WIDTH = 0.9 * DEVICE_WIDTH;
const MY_TEAM_MATCH_HEIGHT = 150;
const MY_TEAM_MATCH_WIDTH = 0.9 * DEVICE_WIDTH;
// const MY_TEAM_OVERVIEW_TITLE_FONT_SIZE = 14;
// const MY_TEAM_OVERVIEW_CONTENT_FONT_SIZE = 14;

export {
  TAB_NAVIGATOR_HEIGTH,
  TAB_NAVIGATOR_LABEL_MARGIN_BOTTOM,
  TAB_NAVIGATOR_LABEL_FONT_SIZE,

  MATCH_HEADER_HEIGHT,
  MATCH_HEADER_DROPDOWN_WIDTH,
  MATCH_HEADER_DROPDOWN_HEIGHT,

  MY_TEAM_HEADER_HEIGHT,
  MY_TEAM_HEADER_DROPDOWN_WIDTH,
  MY_TEAM_HEADER_DROPDOWN_HEIGHT,

  MY_TEAM_OVERVIEW_HEIGHT,
  MY_TEAM_OVERVIEW_WIDTH,
  MY_TEAM_OVERVIEW_TITLE_FONT_SIZE,
  MY_TEAM_OVERVIEW_CONTENT_FONT_SIZE,

  MY_TEAM_MEMBER_HEIGHT,
  MY_TEAM_MEMBER_WIDTH,
  MY_TEAM_MATCH_HEIGHT,
  MY_TEAM_MATCH_WIDTH,
};
