const INITIALIZE_APP_SUCCESS = "INITIALIZE_APP_SUCCESS";
const INITIALIZE_APP_FAIL = "INITIALIZE_APP_FAIL";
const SET_INITIALIZE_ERROR = "SET_INITIALIZE_ERROR";

export {
  INITIALIZE_APP_SUCCESS,
  INITIALIZE_APP_FAIL,
  SET_INITIALIZE_ERROR,
};
